version: '3'

services:
  frontend:
    build: .
    image: datamap_home_page
    container_name: datamap_home_page
    restart: always
    env_file:
      - ${ENV_FILE_PATH}
    ports:
      - '3001:3001'
    networks:
      - gatekeeper_gatekeeper-network

networks:
  gatekeeper_gatekeeper-network:
    driver: bridge
    name: gatekeeper_gatekeeper-network
